# This is a basic workflow to help you get started with Actions

name: Buid Android and IOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  insall-and-test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
     - name: Install npm dependencies
       run: |
          npm install
     - name: Run tests
       run: |
          npm test
          
